#!/bin/bash
TOKEN="91068beafa44f0f4442c67a2c75b94f472be033015abdd7a82fa6bdec225d1b2"
COLLECTION="6a51d3b689432b9105b65065"
BASE="https://api.webflow.com/v2/collections/$COLLECTION/items"

echo "Adding content to Post 1..."
curl -s -X PATCH -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
  "$BASE/6a51d5e05e9255c011cc3749" \
  -d '{"fieldData":{"content":"<p>Georgia has rapidly emerged as one of the most sought-after destinations for international students pursuing medical education. With its combination of affordable tuition fees, globally recognized medical degrees, and English-taught programs, it is no surprise that the country is attracting students from across the Middle East, Africa, and Asia.</p><h3>Affordable Tuition Without Compromising Quality</h3><p>Compared to medical schools in Europe or North America, Georgian universities offer medical programs at a fraction of the cost. Tuition fees typically range from $4,000 to $8,000 per year, making it an accessible option for families seeking quality education without the financial burden.</p><h3>Globally Recognized Degrees</h3><p>Medical degrees obtained from accredited Georgian universities are recognized by major international bodies including the World Health Organization (WHO) and the Educational Commission for Foreign Medical Graduates (ECFMG). This means graduates can pursue residency programs and medical licensing in numerous countries worldwide.</p><h3>English-Taught Programs</h3><p>Most medical universities in Georgia offer complete programs in English, eliminating the language barrier for international students. This allows students to focus entirely on their studies without the additional challenge of learning a new language.</p><h3>A Safe and Welcoming Environment</h3><p>Georgia consistently ranks as one of the safest countries in Europe. Its capital, Tbilisi, offers a vibrant mix of modern amenities and rich cultural heritage, making it an ideal home away from home for international students.</p>"}}' | python3 -c "import sys,json;d=json.load(sys.stdin);print('  Post 1 content: OK')" 2>/dev/null

echo "Adding content to Post 2..."
curl -s -X PATCH -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
  "$BASE/6a51d5e05e9255c011cc3746" \
  -d '{"fieldData":{"content":"<p>Tbilisi, the capital city of Georgia, is home to some of the most prestigious medical universities in the Caucasus region. This comprehensive guide covers everything an aspiring medical student needs to know before making the move.</p><h3>Top Medical Universities in Tbilisi</h3><p>The city boasts several highly-ranked medical institutions including Tbilisi State Medical University (TSMU), which is the oldest and most established medical school in Georgia, founded in 1918. Other notable institutions include the University of Georgia and the Georgian National University.</p><h3>Admission Requirements</h3><p>Admission to medical programs in Tbilisi typically requires a high school diploma with strong grades in biology and chemistry. Most universities conduct entrance interviews, and some require standardized test scores. The application process is straightforward, and many universities offer rolling admissions throughout the year.</p><h3>Student Life in Tbilisi</h3><p>Life in Tbilisi is an incredible experience for international students. The city offers affordable housing, delicious cuisine, a thriving arts scene, and easy access to stunning natural landscapes. The cost of living is significantly lower than in most European capitals, allowing students to enjoy a comfortable lifestyle while focusing on their studies.</p><h3>After Graduation</h3><p>Graduates from Tbilisi medical universities have successfully pursued careers in hospitals and research institutions across the globe. The strong foundation in clinical practice and theoretical knowledge prepares students for licensing exams in the US, UK, EU, and Middle Eastern countries.</p>"}}' | python3 -c "import sys,json;d=json.load(sys.stdin);print('  Post 2 content: OK')" 2>/dev/null

echo "Adding content to Post 3..."
curl -s -X PATCH -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
  "$BASE/6a51d5e05e9255c011cc3743" \
  -d '{"fieldData":{"content":"<p>One of the biggest advantages of studying in Georgia is the affordable cost of living. In this article, we break down the typical monthly expenses for an international student living in Tbilisi.</p><h3>Accommodation: $200 - $500/month</h3><p>Student housing options range from university dormitories ($150-250/month) to private apartments ($300-500/month). Shared apartments are the most popular option, offering privacy and comfort at a reasonable price. Most apartments come fully furnished with all necessary amenities.</p><h3>Food and Groceries: $150 - $250/month</h3><p>Georgia is famous for its cuisine, and eating out is incredibly affordable. A meal at a local restaurant costs between $3-8, while cooking at home can reduce your food budget significantly. Local markets offer fresh produce at very low prices.</p><h3>Transportation: $20 - $40/month</h3><p>Tbilisi has an excellent public transportation system including buses and the metro. A monthly transit pass costs around $15. Taxis are also very affordable, with most rides within the city costing $2-5.</p><h3>Health Insurance: $30 - $60/month</h3><p>International students are required to have health insurance. Several affordable options are available specifically designed for students, covering doctor visits, hospital stays, and emergency care.</p><h3>Total Monthly Budget: $400 - $850</h3><p>With careful planning, a student can live comfortably in Tbilisi for $500-600 per month, making it one of the most affordable student cities in Europe.</p>"}}' | python3 -c "import sys,json;d=json.load(sys.stdin);print('  Post 3 content: OK')" 2>/dev/null

echo "Adding content to Post 4..."
curl -s -X PATCH -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
  "$BASE/6a51d5e05e9255c011cc3740" \
  -d '{"fieldData":{"content":"<p>Eastern Europe has become a hub for international medical education, with several countries offering high-quality English-taught programs. In this article, we compare the most popular destinations to help you make an informed decision.</p><h3>Georgia</h3><p>Georgia offers the most affordable medical programs with tuition starting from $4,000/year. The admission process is relatively simple, and the country offers a warm, welcoming environment for international students. Programs are 6 years and include extensive clinical training.</p><h3>Poland</h3><p>Polish medical universities are known for their rigorous academic standards and modern facilities. Tuition ranges from $10,000-15,000/year. The country offers excellent post-graduation opportunities within the EU.</p><h3>Romania</h3><p>Romania provides quality medical education at moderate prices ($5,000-8,000/year). Many programs are recognized across the EU, and the country offers a rich cultural experience.</p><h3>Making Your Choice</h3><p>The best choice depends on your budget, career goals, and personal preferences. Georgia stands out for its affordability and straightforward admission process, while Poland and Romania offer EU integration benefits. UniStation can help you evaluate your options and find the perfect fit.</p>"}}' | python3 -c "import sys,json;d=json.load(sys.stdin);print('  Post 4 content: OK')" 2>/dev/null

echo "Adding content to Post 5..."
curl -s -X PATCH -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" \
  "$BASE/6a51d5e05e9255c011cc373d" \
  -d '{"fieldData":{"content":"<p>One of the most common concerns for students considering studying medicine abroad is degree recognition. This guide explains how graduates from Georgian medical universities can practice medicine in various countries around the world.</p><h3>United Arab Emirates (UAE)</h3><p>The UAE Ministry of Education requires degree attestation, which involves verifying your degree with the Georgian Ministry of Education, followed by UAE embassy attestation. After that, you will need to pass the UAE licensing exam (DHA, DOH, or MOH) to practice medicine.</p><h3>United Kingdom (PLAB)</h3><p>Graduates from WHO-listed medical schools (which includes accredited Georgian universities) are eligible to take the PLAB test. Passing both parts of PLAB allows you to register with the GMC and practice medicine in the UK.</p><h3>United States (USMLE)</h3><p>Georgian medical graduates are eligible to take the USMLE (United States Medical Licensing Examination). After passing all three steps and completing a residency program, you can practice medicine in the US.</p><h3>European Union</h3><p>Medical degrees from accredited Georgian universities are recognized in many EU countries, though some may require additional language proficiency tests or bridging courses.</p><h3>How UniStation Helps</h3><p>UniStation provides comprehensive support throughout the recognition process, including document preparation, attestation guidance, and exam preparation resources. Our experienced team has helped hundreds of graduates successfully navigate the licensing process in their target countries.</p>"}}' | python3 -c "import sys,json;d=json.load(sys.stdin);print('  Post 5 content: OK')" 2>/dev/null

echo ""
echo "All content added!"